YOUTUBE_TASKS: dict[str, str] = {
    "Boost Your Cats Earnings!": 'dildo',
    "Futures Trading PART 1": 'AIRNODE',
    "Futures Trading PART 2": 'WEI',
    "FREE Crypto": 'dip',
    "How To Make 10x On Crypto": 'ABSTRACT',
    "How To Make 10x On Crypto PART 2": 'AUCTION',
    "How To Make 10x On Crypto PART 3": 'AUDIT',
    "Earn $1000 Just by Listening To Music!": 'BAG',
    "Make Money Online For Free": 'AFFILIATE',
    "GET RICH NOW": 'BAKERS',
    "How to Stay Productive": 'ALTCOIN',
    "Start From ZERO": 'ALPHA',
    "Productivity Tips!": 'BAKING',
    "Make $100,000 in 6 Months": 'MAINNET',
    "Easy Crypto Airdrops": 'MARKET',
    "Job Without a Degree": 'LAMBO',
    "Learned to Code!": 'LEDGER',
    "Pinterest Affiliate Marketing": 'BITSTREAM',
    "GET FREE MONEY NOW!": 'OPTION',
    "Start Earning Now!": 'BOTS',
    "EARN $30 PER WORD": 'BLOCK',
    "Make $5,000+ Per MONTH": 'BITCOINER',
    "Amazon Success!": 'OPTION',
    "Top Shocking Ways": 'ASSET',
    "Change Your Life!": 'BOUNTY',
    "FREE Money From Rich People!": 'BASKET',
    "BLOCKCHAIN TIPS": 'BRIDGES',
    "Earn on YouTube Anonymously!": 'CIPHER',
    "Maximize Your Savings ": 'DUMPING',
    "Make Money on YouTube!": 'CHARGEBACK',
    "Earn Cash Back": 'DOTSAMA',
    "Save Money on Shopping": 'COORDINATOR',
    "Sell Your Photos Online": 'CONSENSUS',
    "How to Reupload Free Videos?": 'CASH',
    "BUSINESS WITH 100$": 'CRYPTOLOGY',
    "EARN FROM HOME": 'CRYPTOJACKING',
    "PASSIVE INCOME": 'CRYPTOGRAPHY',
    "Small Business Ideas!!": 'CRYPTOASSET',
    "Videos Legally for YouTube Profit": 'CUSTODIAN',
    "Money on YouTube": 'DEFLATION',
    "How Blockchain ACTUALLY Work": 'DIGITAL',
    "Earn Money with Amazon!!!": 'DIFFICULTY',
    "Legally Reupload Videos": 'CRYPTOLOGY',
    "Earn Online by Reuploading": 'CURRENCY',
    "Blockchain Demystified": 'DRIVECHAIN',
    "Amazon Success": 'DEFI'
}

